apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: animequotesapp
  name: animequotesapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: animequotesapp
  strategy: {}
  template:
    metadata:
      labels:
        app: animequotesapp
    spec:
      containers:
        - image: chinmaykubal/animequotesapp:20
          name: animequotesapp
          ports:
            - containerPort: 3000
          resources: {}
status: {}
