apiVersion: v1
kind: Service
metadata:
  labels:
    app: animequotesapp
  name: animequotesapp-svc
  namespace: animequotes-ns
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: animequotesapp
  type: LoadBalancer
